import localFont from "next/font/local";
import "./globals.css";
import Slidebar from "@/components/Slidebar";
import SlidebarM from "@/components/Mobile/SlidebarM";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col lg:flex lg:flex-row lg:justify-between `}
      >
        <Slidebar/>
        <SlidebarM/>
        {children}
      </body>
    </html>
  );
}
